import { useParams, useNavigate } from 'react-router-dom';
import { MainLayout } from '@/components/layout/MainLayout';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Skeleton } from '@/components/ui/skeleton';
import { useCarDetail } from '@/hooks/useFleetData';
import { ArrowLeft, Car, Calendar, DollarSign, Wrench, AlertTriangle, Shield, FileText, Edit, TrendingUp, TrendingDown } from 'lucide-react';

export default function VehicleDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { car, rentals, expenses, maintenanceTickets, fines, insurance, rego, isLoading, isError } = useCarDetail(id);

  if (isLoading) return <MainLayout title="Loading..."><Skeleton className="h-64" /></MainLayout>;
  if (isError || !car) return (<MainLayout title="Vehicle Not Found"><div className="flex flex-col items-center justify-center py-16"><p className="text-muted-foreground mb-4">The vehicle you're looking for doesn't exist.</p><Button onClick={() => navigate('/fleet')}>Back to Fleet</Button></div></MainLayout>);

  const totalRevenue = rentals.reduce((sum, r) => sum + Number(r.total_amount || 0), 0);
  const totalExpenses = expenses.reduce((sum, e) => sum + Number(e.amount || 0), 0);
  const netIncome = totalRevenue - totalExpenses;
  const roi = Number(car.purchase_price) > 0 ? ((netIncome / Number(car.purchase_price)) * 100).toFixed(1) : '0';

  return (
    <MainLayout title={`${car.make} ${car.model}`} subtitle={car.plate_number}>
      <div className="flex items-center justify-between mb-6">
        <Button variant="ghost" onClick={() => navigate('/fleet')}><ArrowLeft className="w-4 h-4 mr-2" /> Back to Fleet</Button>
        <div className="flex gap-2"><Button variant="outline"><Edit className="w-4 h-4 mr-2" /> Edit</Button>{car.status !== 'sold' && <Button variant="destructive">Mark as Sold</Button>}</div>
      </div>
      <Card className="mb-6"><CardContent className="p-6"><div className="flex flex-col lg:flex-row gap-6"><div className="w-full lg:w-64 h-48 bg-muted rounded-lg flex items-center justify-center overflow-hidden">{car.images?.[0] ? <img src={car.images[0]} alt={`${car.make} ${car.model}`} className="w-full h-full object-cover" /> : <Car className="w-16 h-16 text-muted-foreground" />}</div><div className="flex-1 grid grid-cols-2 md:grid-cols-4 gap-4"><div><p className="text-sm text-muted-foreground">Status</p><StatusBadge status={car.status} className="mt-1" /></div><div><p className="text-sm text-muted-foreground">Year</p><p className="font-medium">{car.year}</p></div><div><p className="text-sm text-muted-foreground">Body Type</p><p className="font-medium">{car.body_type || '-'}</p></div><div><p className="text-sm text-muted-foreground">Color</p><p className="font-medium">{car.color || '-'}</p></div><div><p className="text-sm text-muted-foreground">Plate Number</p><p className="font-mono font-medium">{car.plate_number}</p></div><div><p className="text-sm text-muted-foreground">Purchase Price</p><p className="font-medium">${Number(car.purchase_price || 0).toLocaleString()}</p></div><div><p className="text-sm text-muted-foreground">Purchase Date</p><p className="font-medium">{car.purchase_date ? new Date(car.purchase_date).toLocaleDateString() : '-'}</p></div><div><p className="text-sm text-muted-foreground">Tracker IMEI</p><p className="font-mono text-sm">{car.tracker_imei || 'N/A'}</p></div></div></div></CardContent></Card>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <Card><CardContent className="p-4"><div className="flex items-center gap-3"><div className="p-2 rounded-lg bg-success/10"><DollarSign className="w-5 h-5 text-success" /></div><div><p className="text-sm text-muted-foreground">Total Revenue</p><p className="text-xl font-bold">${totalRevenue.toLocaleString()}</p></div></div></CardContent></Card>
        <Card><CardContent className="p-4"><div className="flex items-center gap-3"><div className="p-2 rounded-lg bg-destructive/10"><TrendingDown className="w-5 h-5 text-destructive" /></div><div><p className="text-sm text-muted-foreground">Total Expenses</p><p className="text-xl font-bold">${totalExpenses.toLocaleString()}</p></div></div></CardContent></Card>
        <Card><CardContent className="p-4"><div className="flex items-center gap-3"><div className={`p-2 rounded-lg ${netIncome >= 0 ? 'bg-success/10' : 'bg-destructive/10'}`}><TrendingUp className={`w-5 h-5 ${netIncome >= 0 ? 'text-success' : 'text-destructive'}`} /></div><div><p className="text-sm text-muted-foreground">Net Income</p><p className={`text-xl font-bold ${netIncome >= 0 ? 'text-success' : 'text-destructive'}`}>${netIncome.toLocaleString()}</p></div></div></CardContent></Card>
        <Card><CardContent className="p-4"><div className="flex items-center gap-3"><div className="p-2 rounded-lg bg-accent/10"><TrendingUp className="w-5 h-5 text-accent" /></div><div><p className="text-sm text-muted-foreground">ROI</p><p className="text-xl font-bold">{roi}%</p></div></div></CardContent></Card>
      </div>
      <Tabs defaultValue="summary" className="space-y-4">
        <TabsList><TabsTrigger value="summary">Summary</TabsTrigger><TabsTrigger value="rentals">Rental History ({rentals.length})</TabsTrigger><TabsTrigger value="maintenance">Maintenance ({maintenanceTickets.length})</TabsTrigger><TabsTrigger value="fines">Fines ({fines.length})</TabsTrigger></TabsList>
        <TabsContent value="summary"><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Shield className="w-5 h-5" /> Insurance</CardTitle></CardHeader><CardContent>{insurance ? (<div className="space-y-3"><div className="flex justify-between"><span className="text-muted-foreground">Provider</span><span className="font-medium">{insurance.provider}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Policy Number</span><span className="font-mono">{insurance.policy_number}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Expiry Date</span><span className="font-medium">{new Date(insurance.expiry_date).toLocaleDateString()}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Premium</span><span className="font-medium">${insurance.premium_amount}</span></div></div>) : <p className="text-muted-foreground">No insurance record found</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="w-5 h-5" /> Registration</CardTitle></CardHeader><CardContent>{rego ? (<div className="space-y-3"><div className="flex justify-between"><span className="text-muted-foreground">Rego Number</span><span className="font-mono">{rego.rego_number}</span></div><div className="flex justify-between"><span className="text-muted-foreground">State</span><span className="font-medium">{rego.state}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Expiry Date</span><span className="font-medium">{new Date(rego.expiry_date).toLocaleDateString()}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Renewal Amount</span><span className="font-medium">${rego.renewal_amount}</span></div></div>) : <p className="text-muted-foreground">No registration record found</p>}</CardContent></Card></div></TabsContent>
        <TabsContent value="rentals"><Card><CardHeader><CardTitle>Rental History</CardTitle></CardHeader><CardContent>{rentals.length > 0 ? (<div className="space-y-4">{rentals.map((rental) => (<div key={rental.id} className="flex items-center justify-between p-4 bg-muted/50 rounded-lg"><div className="flex items-center gap-4"><div className="w-10 h-10 rounded-full bg-info/20 flex items-center justify-center"><Calendar className="w-5 h-5 text-info" /></div><div><p className="font-medium">{rental.renter?.first_name} {rental.renter?.last_name}</p><p className="text-sm text-muted-foreground">{new Date(rental.start_date).toLocaleDateString()} - {rental.end_date ? new Date(rental.end_date).toLocaleDateString() : 'Ongoing'}</p></div></div><div className="text-right"><p className="font-medium">${Number(rental.total_amount || 0).toLocaleString()}</p><StatusBadge status={rental.status} /></div></div>))}</div>) : <p className="text-muted-foreground text-center py-8">No rental history</p>}</CardContent></Card></TabsContent>
        <TabsContent value="maintenance"><Card><CardHeader><CardTitle>Maintenance History</CardTitle></CardHeader><CardContent>{maintenanceTickets.length > 0 ? (<div className="space-y-4">{maintenanceTickets.map((ticket) => (<div key={ticket.id} className="flex items-center justify-between p-4 bg-muted/50 rounded-lg"><div className="flex items-center gap-4"><div className="w-10 h-10 rounded-full bg-warning/20 flex items-center justify-center"><Wrench className="w-5 h-5 text-warning" /></div><div><p className="font-medium">{ticket.title}</p><p className="text-sm text-muted-foreground">{ticket.description}</p></div></div><div className="text-right"><StatusBadge status={ticket.status} /><p className="text-sm text-muted-foreground mt-1">{ticket.actual_cost ? `$${ticket.actual_cost}` : ticket.estimated_cost ? `Est. $${ticket.estimated_cost}` : ''}</p></div></div>))}</div>) : <p className="text-muted-foreground text-center py-8">No maintenance records</p>}</CardContent></Card></TabsContent>
        <TabsContent value="fines"><Card><CardHeader><CardTitle>Traffic Fines</CardTitle></CardHeader><CardContent>{fines.length > 0 ? (<div className="space-y-4">{fines.map((fine) => (<div key={fine.id} className="flex items-center justify-between p-4 bg-muted/50 rounded-lg"><div className="flex items-center gap-4"><div className="w-10 h-10 rounded-full bg-destructive/20 flex items-center justify-center"><AlertTriangle className="w-5 h-5 text-destructive" /></div><div><p className="font-medium">${fine.amount}</p><p className="text-sm text-muted-foreground">{fine.description}</p></div></div><div className="text-right"><StatusBadge status={fine.is_paid ? 'paid' : 'unpaid'} /><p className="text-sm text-muted-foreground mt-1">{new Date(fine.offence_date).toLocaleDateString()}</p></div></div>))}</div>) : <p className="text-muted-foreground text-center py-8">No traffic fines</p>}</CardContent></Card></TabsContent>
      </Tabs>
    </MainLayout>
  );
}
